<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view_alter().
 */
function handlebars_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // @todo Make this configurable i.e. nodes, terms, every page, specific pages, etc.
  $entity_types = [
    'node',
    'taxonomy_term',
  ];
  if (!in_array($entity->getEntityType()->id(), $entity_types)) {
    return;
  }

  /** @var \Drupal\handlebars\Service\HandlebarsService $handlebars_service */
  $handlebars_service = \Drupal::service('handlebars.service');
  $handlebars_service->attachLibraries($build, $entity);
}

/**
 * Implements hook_library_info_alter().
 */
function handlebars_library_info_alter(&$libraries, $extension) {
  \Drupal::service('handlebars.service')->libraryInfoAlter($libraries, $extension);
}

/**
 * Implements hook_page_attachments_alter().
 */
function handlebars_page_attachments_alter(array &$attachments) {
  // Avoid attaching libraries on admin themes.
  // @todo make this configurable.
  if (\Drupal::theme()->getActiveTheme()->getName()
    !== \Drupal::config('system.theme')->get('default')
  ) {
    return;
  }

  // @todo Add libraries globally based on configuration.
  /** @var \Drupal\handlebars\Service\HandlebarsService $handlebars_service */
  $handlebars_service = \Drupal::service('handlebars.service');
  $handlebars_service->attachLibraries($attachments, '');

  // Add drupalSettings.
  $attachments['#attached']['drupalSettings']['Handlebars'] = [
    'compiledHandlebars' => $handlebars_service->preCompileEnabled(),
  ];
}
